# Environment setup                           
num_drone: 10
num_obs: 0
config: circle  # circle, random, custom

# Parameters

n_order: 8
n_derivative: 4

dt_opt: 0.1
dt_mpc: 0.1
dt_upd: 0.05

T_hor: 3
T_max: 10

# Constraints
x_lim: [-2.6, 2.6]
y_lim: [-2.6, 2.6]
z_lim: [0.4, 2]

vel_max: 1.5
acc_max: 1.5

env_drone: [0.12, 0.12, 0.2]

f_safe: 2.5

kappa: 5
weight_goal: 100
weight_quad: 5000
weight_line: 50000

weight_vel: 0
weight_acc: 0.1
weight_jrk: 1

# Circle configuration
radius: 2.4
height: 1.2

# Custom configuration

pos_static_obs: [[2.44, 0.61, 0],
                [0.61, 1.22, 0],
                [-1.83, 1.22, 0],
                [-1.22, 0, 0],
                [-1.22, -1.22, 0],
                [-0.61, -3.05, 0],
                [0.61, -1.83, 0],
                [1.22, -1.22, 0],
                [1.83, -3.05, 0],
                [3.05, -1.22, 0]]

dim_static_obs: [[+0.25, +0.25, 8.0],            
                [+0.25, +0.25, 8.0],             
                [+0.25, +0.25, 8.0],             
                [+0.25, +0.25, 8.0],             
                [+0.25, +0.25, 8.0],            
                [+0.25, +0.25, 8.0],             
                [+0.25, +0.25, 8.0],             
                [+0.25, +0.25, 8.0],             
                [+0.25, +0.25, 8.0],             
                [+0.25, +0.25, 8.0]] 
                

init_drone:  [[1.83, 1.22, 0.5],
              [0.61, 2.44, 0.5],
              [-2.44, 0.61, 0.5],
              [-1.83, -0.61, 0.5],
              [-2.44, -3.05, 0.5],
              [0, -0.61, 0.5],
              [0.61, -3.05, 0.5],
              [2.44, -1.83, 0.5]]

goal_drone: [[-2.44, -3.05, 0.5],
             [0, -0.61, 0.5],
             [0.61, -3.05, 0.5],
             [2.44, -1.83, 0.5],
             [1.83, 1.22, 0.5],
             [0.61, 2.44, 0.5],
             [-2.44, 0.61, 0.5],
             [-1.83, -0.61, 0.5]]
